create table if not exists public.device_status (
  device_id text primary key,
  latitude double precision,
  longitude double precision,
  address text,
  location_source text check (location_source in ('GPS', 'WPS', 'NONE')),
  location_accuracy double precision,
  current_track integer not null default 0,
  total_tracks integer not null default 0,
  is_playing boolean not null default false,
  volume integer not null default 0 check (volume between 0 and 30),
  heart_rate integer,
  device_powered_on boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.device_status enable row level security;
alter table public.device_status add column if not exists device_powered_on boolean not null default true;
-- The browser reads initial state through the Next.js server route.
-- Realtime requires a SELECT policy for the browser's publishable key.
drop policy if exists "caregivers can read device status" on public.device_status;
create policy "caregivers can read device status"
  on public.device_status for select
  to anon, authenticated
  using (true);

create table if not exists public.device_commands (
  id bigint generated by default as identity primary key,
  device_id text not null,
  command text not null check (command in ('play_pause', 'next_track', 'previous_track', 'play_track')),
  track integer,
  status text not null default 'pending' check (status in ('pending', 'delivered')),
  created_at timestamptz not null default now(),
  delivered_at timestamptz
);

create index if not exists device_commands_pending_idx
  on public.device_commands (device_id, status, created_at);

alter table public.device_commands enable row level security;
-- Commands are created and consumed only by the Next.js server using its service role.
-- No browser insert/update policy is intentionally granted.

alter table public.device_status replica identity full;

-- Supabase may already have added this table to Realtime. Keep this migration
-- safe to rerun instead of failing with SQLSTATE 42710.
do $$
begin
  if not exists (
    select 1
    from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_namespace n on n.oid = c.relnamespace
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime'
      and n.nspname = 'public'
      and c.relname = 'device_status'
  ) then
    alter publication supabase_realtime add table public.device_status;
  end if;
end
$$;

-- Caregiver-defined safety zone and warning thresholds.
create table if not exists public.device_alert_settings (
  device_id text primary key references public.device_status(device_id) on delete cascade,
  alerts_enabled boolean not null default true,
  alert_email text not null default 'kakarla_hemanth_reddy@s2026.ssts.edu.sg',
  geofence_enabled boolean not null default false,
  zone_label text not null default 'Home zone',
  zone_latitude double precision,
  zone_longitude double precision,
  zone_radius_m integer not null default 200 check (zone_radius_m between 25 and 50000),
  heart_rate_enabled boolean not null default false,
  max_heart_rate integer not null default 120 check (max_heart_rate between 40 and 250),
  last_geofence_alert_at timestamptz,
  last_heart_rate_alert_at timestamptz,
  updated_at timestamptz not null default now()
);

-- Existing projects created before alerting existed: add the columns if missing.
alter table public.device_alert_settings add column if not exists alerts_enabled boolean not null default true;
alter table public.device_alert_settings add column if not exists alert_email text not null default 'kakarla_hemanth_reddy@s2026.ssts.edu.sg';
alter table public.device_alert_settings add column if not exists geofence_enabled boolean not null default false;
alter table public.device_alert_settings add column if not exists zone_label text not null default 'Home zone';
alter table public.device_alert_settings add column if not exists zone_latitude double precision;
alter table public.device_alert_settings add column if not exists zone_longitude double precision;
alter table public.device_alert_settings add column if not exists zone_radius_m integer not null default 200;
alter table public.device_alert_settings add column if not exists heart_rate_enabled boolean not null default false;
alter table public.device_alert_settings add column if not exists max_heart_rate integer not null default 120;
alter table public.device_alert_settings add column if not exists last_geofence_alert_at timestamptz;
alter table public.device_alert_settings add column if not exists last_heart_rate_alert_at timestamptz;
alter table public.device_alert_settings add column if not exists updated_at timestamptz not null default now();

-- Every warning the system raises, with the outcome of its email delivery.
create table if not exists public.device_alerts (
  id bigint generated by default as identity primary key,
  device_id text not null,
  kind text not null check (kind in ('geofence_exit', 'heart_rate_high', 'recovery', 'test')),
  message text not null,
  detail jsonb not null default '{}'::jsonb,
  email_to text,
  email_status text not null default 'skipped' check (email_status in ('sent', 'failed', 'skipped')),
  email_error text,
  is_test boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists device_alerts_recent_idx
  on public.device_alerts (device_id, created_at desc);

alter table public.device_alert_settings enable row level security;
alter table public.device_alerts enable row level security;
-- Both tables are written and read by the Next.js server with its service role.
-- No browser policy is intentionally granted.

insert into public.device_status (device_id)
values ('pwd-001')
on conflict (device_id) do nothing;

insert into public.device_alert_settings (device_id)
values ('pwd-001')
on conflict (device_id) do nothing;
