create table if not exists public.device_status (
  device_id text primary key,
  latitude double precision,
  longitude double precision,
  address text,
  location_source text check (location_source in ('GPS', 'WPS', 'NONE')),
  location_accuracy double precision,
  current_track integer not null default 0,
  total_tracks integer not null default 0,
  is_playing boolean not null default false,
  volume integer not null default 0 check (volume between 0 and 30),
  heart_rate integer,
  device_powered_on boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.device_status enable row level security;
alter table public.device_status add column if not exists device_powered_on boolean not null default true;
-- The browser reads initial state through the Next.js server route.
-- Realtime requires a SELECT policy for the browser's publishable key.
drop policy if exists "caregivers can read device status" on public.device_status;
create policy "caregivers can read device status"
  on public.device_status for select
  to anon, authenticated
  using (true);

create table if not exists public.device_commands (
  id bigint generated by default as identity primary key,
  device_id text not null,
  command text not null check (command in ('play_pause', 'next_track', 'previous_track', 'play_track')),
  track integer,
  status text not null default 'pending' check (status in ('pending', 'delivered')),
  created_at timestamptz not null default now(),
  delivered_at timestamptz
);

create index if not exists device_commands_pending_idx
  on public.device_commands (device_id, status, created_at);

alter table public.device_commands enable row level security;
-- Commands are created and consumed only by the Next.js server using its service role.
-- No browser insert/update policy is intentionally granted.

alter table public.device_status replica identity full;

-- Supabase may already have added this table to Realtime. Keep this migration
-- safe to rerun instead of failing with SQLSTATE 42710.
do $$
begin
  if not exists (
    select 1
    from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_namespace n on n.oid = c.relnamespace
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime'
      and n.nspname = 'public'
      and c.relname = 'device_status'
  ) then
    alter publication supabase_realtime add table public.device_status;
  end if;
end
$$;

insert into public.device_status (device_id)
values ('pwd-001')
on conflict (device_id) do nothing;
